### ISSUE TITLE
Issue when trying to export node group.

### ISSUE THREAD

**Issue by BoondaProd** [LucaRood/Blib#3]
Platform: Windows 10
Blender Version: 2.77

When I run `bexport(bpy.types.ShaderNodeTree, "desktop/r6snodegroup.blib")` in the console I get the error: `Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\belin\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\modules\blib\cycles\bexport.py", line 93, in bexport
    check_asset(asset, True)
  File "C:\Users\belin\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\modules\blib\cycles\utils.py", line 69, in check_asset
    raise InvalidObject("Object passed is not a material or node group.")
blib.exceptions.InvalidObject: Object passed is not a material or node group.` 
Here are the areas in question, please help me fix this, as I do not know much python. (Bexport, line 93) (Utils, line 69)
![bexport error line](https://user-images.githubusercontent.com/35624479/35181835-8bc77992-fe1d-11e7-9285-917d138eea56.JPG)
![utils error line](https://user-images.githubusercontent.com/35624479/35181836-92bde1c8-fe1d-11e7-988a-ac5578c6be96.JPG)
Thanks, Boonda

**Comment by BoondaProd** [comment]
Sorry figured it out myself. :)
